-- MySQL Script generated by MySQL Workbench
-- Sun Feb 13 17:27:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hungergames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hungergames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hungergames` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hungergames` ;

-- -----------------------------------------------------
-- Table `hungergames`.`alliances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`alliances` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`alliances` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ally1` BIGINT NULL,
  `ally2` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `ally1_idx` (`ally1` ASC) VISIBLE,
  INDEX `ally2_idx` (`ally2` ASC) VISIBLE,
  CONSTRAINT `ally1`
    FOREIGN KEY (`ally1`)
    REFERENCES `hungergames`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ally2`
    FOREIGN KEY (`ally2`)
    REFERENCES `hungergames`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`characters` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`characters` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `last_ate` INT NOT NULL DEFAULT 1,
  `environment` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`events` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `author` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`outcomes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`outcomes` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`outcomes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `outcome_scene_id` BIGINT NULL,
  `type` TINYINT NULL,
  `effect` VARCHAR(225) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `scene_id_idx` (`outcome_scene_id` ASC) VISIBLE,
  CONSTRAINT `outcome_scene_id`
    FOREIGN KEY (`outcome_scene_id`)
    REFERENCES `hungergames`.`scenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`requirements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`requirements` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`requirements` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `requirement_scene_id` BIGINT NULL,
  `requirement` VARCHAR(45) NULL,
  `role` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `requirement_scene_id_idx` (`requirement_scene_id` ASC) VISIBLE,
  CONSTRAINT `requirement_scene_id`
    FOREIGN KEY (`requirement_scene_id`)
    REFERENCES `hungergames`.`scenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`scene_stack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`scene_stack` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`scene_stack` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `scene_id` BIGINT NULL,
  `in_progress` TINYINT NULL DEFAULT 1,
  `winning_vote` BIGINT NULL DEFAULT -1,
  `flavor` VARCHAR(1024) NULL DEFAULT '',
  `participants` VARCHAR(8) NULL,
  PRIMARY KEY (`id`),
  INDEX `scene_id_idx` (`scene_id` ASC) VISIBLE,
  INDEX `winning_vote_idx` (`winning_vote` ASC) VISIBLE,
  CONSTRAINT `scene_id`
    FOREIGN KEY (`scene_id`)
    REFERENCES `hungergames`.`scenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `winning_vote`
    FOREIGN KEY (`winning_vote`)
    REFERENCES `hungergames`.`votes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`scenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`scenes` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`scenes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `scene_name` VARCHAR(45) NULL,
  `num_requirements` INT NULL DEFAULT 0,
  `num_outcomes` INT NULL,
  `occurrences` INT NULL DEFAULT 0,
  `participants` TINYINT NULL DEFAULT 1,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`statuses` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`statuses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `character_id` BIGINT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `character_id_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `character_id`
    FOREIGN KEY (`character_id`)
    REFERENCES `hungergames`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`users` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passhash` VARCHAR(1024) NULL,
  `voting_chances` INT NULL DEFAULT 0,
  `positive_votes` INT NULL DEFAULT 0,
  `neutral_votes` INT NULL DEFAULT 0,
  `negative_votes` INT NULL DEFAULT 0,
  `valid_voter` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`users_characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`users_characters` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`users_characters` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `character_id` BIGINT NOT NULL,
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `character_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `hungergames`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `character`
    FOREIGN KEY (`character_id`)
    REFERENCES `hungergames`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hungergames`.`votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`votes` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`votes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `scene_stack_id` BIGINT NULL,
  `voter_id` BIGINT NULL,
  `chosen_outcome` BIGINT NULL,
  `in_progress` TINYINT NULL DEFAULT 1,
  `has_chosen_outcome` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `scene_stack_id_idx` (`scene_stack_id` ASC) VISIBLE,
  INDEX `chosen_outcome_idx` (`chosen_outcome` ASC) VISIBLE,
  INDEX `voter_id_idx` (`voter_id` ASC) VISIBLE,
  CONSTRAINT `scene_stack_id`
    FOREIGN KEY (`scene_stack_id`)
    REFERENCES `hungergames`.`scene_stack` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `voter_id`
    FOREIGN KEY (`voter_id`)
    REFERENCES `hungergames`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chosen_outcome`
    FOREIGN KEY (`chosen_outcome`)
    REFERENCES `hungergames`.`outcomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
