-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 01:29:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hungergames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hungergames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hungergames` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hungergames` ;

-- -----------------------------------------------------
-- Table `hungergames`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`actor` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`actor` (
  `id` INT NOT NULL,
  `environment` VARCHAR(255) NULL DEFAULT NULL,
  `last_ate` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`outcome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`outcome` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`outcome` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `effect` VARCHAR(255) NULL DEFAULT NULL,
  `scene_id` INT NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`performance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`performance` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`performance` (
  `id` INT NOT NULL,
  `flavor` VARCHAR(255) NULL DEFAULT NULL,
  `in_progress` BIT(1) NOT NULL,
  `participants` VARCHAR(255) NULL DEFAULT NULL,
  `scene_id` INT NULL DEFAULT NULL,
  `time` INT NULL DEFAULT NULL,
  `winning_vote` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`requirement` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`requirement` (
  `id` INT NOT NULL,
  `requirement` VARCHAR(255) NULL DEFAULT NULL,
  `role` INT NULL DEFAULT NULL,
  `scene_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`scene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`scene` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`scene` (
  `id` INT NOT NULL,
  `brief_description` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `num_outcomes` INT NULL DEFAULT NULL,
  `num_participants` INT NULL DEFAULT NULL,
  `num_requirements` INT NULL DEFAULT NULL,
  `occurrences` INT NULL DEFAULT NULL,
  `priority` INT NULL DEFAULT NULL,
  `scene_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`status` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`status` (
  `id` INT NOT NULL,
  `character_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`time` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`time` (
  `id` INT NOT NULL,
  `time` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`user` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `negative_votes` INT NULL DEFAULT NULL,
  `neutral_votes` INT NULL DEFAULT NULL,
  `passhash` VARCHAR(255) NULL DEFAULT NULL,
  `positive_votes` INT NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `valid_voter` BIT(1) NULL DEFAULT NULL,
  `voting_chances` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hungergames`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hungergames`.`vote` ;

CREATE TABLE IF NOT EXISTS `hungergames`.`vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chosen_outcome_id` INT NULL DEFAULT NULL,
  `has_chosen_outcome` BIT(1) NOT NULL,
  `in_progress` BIT(1) NOT NULL,
  `performance_id` INT NULL DEFAULT NULL,
  `voter_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
